name: NPM Publish
on:
  release:
    types: [published, edited]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      
      - name: Installing yarn
        run: npm install -g yarn
        
      - name: Installing dependencies
        run: yarn install --frozen-lockfile
      
      - name: Running test cases
        run: yarn run pdn:test
