name: NPM Publish
on:
  release:
    types: [published, edited]

jobs:
  tests:
    name: Running Test Cases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install -g yarn
      - run: |
            yarn install --frozen-lockfile
            yarn run pdn:test
